### PR TITLE
Unify placement of `set -e` and `set -x`

### PR DESCRIPTION
**Pull request by Blackhex**
Just makes the code more unified. In some scripts the `set -e` and `set -x` was missing though.

### CODE REVIEW

**Comment by eukarpov** [comment]
Maybe it makes sense to control settings only from the workflow. wdyt?

**Comment by Blackhex** [comment]
> Maybe it makes sense to control settings only from the workflow. wdyt?

The intention is to keep the individual steps scripts self-contained so one can execute them separately during the development.

**Comment by eukarpov** [comment]
yeah, it is what I was thinking.

**Review by eukarpov — APPROVED** [review]

**Comment by Blackhex** [comment]
This PR become useless after merging https://github.com/ZacWalk/mingw-woarm64-build/pull/49

**Pull request closed without merging**
